f = open('madlibs.txt', 'w')
adj = input('Enter an adjective: ')
f_noun = input('Enter a noun: ')
verb = input('Enter a verb: ')
s_noun = input('Enter a noun: ')
text = 'The %s panda walked to the %s and then %s. A nearby %s was unaffected by these events.' % (adj, f_noun, verb, s_noun)
print(text)
f.write(text)
f.close()
